INSERT INTO rangos (name, control, description) VALUES ('General de alianza', 1, 'Rango de alianza');
INSERT INTO rangos (name, control, description) VALUES ('General', 2, 'Rango de alianza');
INSERT INTO rangos (name, control, description) VALUES ('Teniente', 3, 'Rango de alianza');
INSERT INTO rangos (name, control, description) VALUES ('Coronel', 4, 'Rango de alianza');
INSERT INTO rangos (name, control, description) VALUES ('Suboficial', 5, 'Rango de alianza');
INSERT INTO rangos (name, control, description) VALUES ('Mayor', 6, 'Rango de alianza');
INSERT INTO rangos (name, control, description) VALUES ('Capitán', 7, 'Rango de alianza');
INSERT INTO rangos (name, control, description) VALUES ('Alférez', 8, 'Rango de alianza');
INSERT INTO rangos (name, control, description) VALUES ('Sargento', 9, 'Rango de alianza');
INSERT INTO rangos (name, control, description) VALUES ('Cabo', 10, 'Rango de alianza');
INSERT INTO rangos (name, control, description) VALUES ('Diplomatico', 11, 'Rango de alianza');
INSERT INTO rangos (name, control, description) VALUES ('Soldado', 12, 'Rango de alianza');
INSERT INTO rangos (name, control, description) VALUES ('Milicia', 13, 'Rango de alianza');
INSERT INTO rangos (name, control, description) VALUES ('Civil', 14, 'Rango de alianza');
INSERT INTO rangos (name, control, description) VALUES ('Insubordinado', 15, 'Rango de alianza');
INSERT INTO rangos (name, control, description) VALUES ('Ausente', 16, 'Rango de alianza');
INSERT INTO rangos (name, control, description) VALUES ('Secundario', 17, 'Rango de alianza');
INSERT INTO rangos (name, control, description) VALUES ('Aspirante', 18, 'Rango de alianza');

INSERT INTO eventos (name, points, description) VALUES ('defprismaganada', 6, 'Defensa de prisma ganada');
INSERT INTO eventos (name, points, description) VALUES ('avaconpelea', 5, 'AvA con pelea');
INSERT INTO eventos (name, points, description) VALUES ('avasinpelea', 3, 'AvA sin pelea');
INSERT INTO eventos (name, points, description) VALUES ('defensapercoganada', 3, 'Defensa de recaudador ganada');
INSERT INTO eventos (name, points, description) VALUES ('defprismaperdida', 2, 'Defensa de prisma perdida');
INSERT INTO eventos (name, points, description) VALUES ('ataqueprisma', 2, 'Ataque a prisma ganado');
INSERT INTO eventos (name, points, description) VALUES ('ataqueperco', 1, 'Ataque a recaudador ganado');
INSERT INTO eventos (name, points, description) VALUES ('prismaviable', 1, 'Encontrar prisma viable');
INSERT INTO eventos (name, points, description) VALUES ('reciclado', 1, 'Reciclado');

INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Avalonicus', 1, '2012-09-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Ammy', 2, '2012-10-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Vulnerant', 2, '2012-11-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Eira-vp', 3, '2012-12-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Kirito-klein', 3, '2013-01-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Mauruz', 3, '2013-02-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Adhemetra', 5, '2013-03-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Elvulne', 5, '2013-04-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Lewans', 5, '2013-05-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Tank-Mauruz', 5, '2013-06-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('The-Mauruz', 5, '2013-07-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Vickypi', 5, '2013-08-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Vulnerant-lil', 5, '2013-09-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Cronology', 6, '2013-10-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Estevi', 6, '2013-11-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Frashirama', 6, '2013-12-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Stiv-xx', 7, '2014-01-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Xvita', 7, '2014-02-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Eucaristia', 8, '2014-03-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Moneda-xdd', 8, '2014-04-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Omegasxx', 8, '2014-05-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Chimuelooh', 9, '2014-06-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Koolhaas', 9, '2014-07-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Nowiie', 9, '2014-08-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Sramar', 9, '2014-09-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Atabex', 10, '2014-10-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Chaapaa', 10, '2014-11-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Chary', 10, '2014-12-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Dark-pizarro', 10, '2015-01-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Drajomut', 10, '2015-02-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Kugh', 10, '2015-03-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Mifequita', 10, '2015-04-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Mr-Tymo', 10, '2015-05-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Nyitiac', 10, '2015-06-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Skurah', 10, '2015-07-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('The-Flynn', 10, '2015-08-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Ukami', 10, '2015-09-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Yatanokagami', 10, '2015-10-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Assesain', 12, '2015-11-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Eve-Ani', 12, '2015-12-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Ffelipe', 12, '2016-01-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Frodobolson', 12, '2016-02-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Gabilinda', 12, '2016-03-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Hare-jp', 12, '2016-04-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Helenthile', 12, '2016-05-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Herakles-Tsuk', 12, '2016-06-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Jack-frostt', 12, '2016-07-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Kefi-[Rub]', 12, '2016-08-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Na-bolom', 12, '2016-09-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Nattew-Zoldyck', 12, '2016-10-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Nightzel', 12, '2016-11-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Okhoye', 12, '2016-12-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Pandita-Milagrosa', 12, '2017-01-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Primm-[Rub]', 12, '2017-02-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Razoback', 12, '2017-03-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Serindipia', 12, '2017-04-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Son-Eternal', 12, '2017-05-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Taisuki', 12, '2017-06-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Trafalgar-A', 12, '2017-07-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Verliebtheit', 12, '2017-08-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Wololo-Knight', 12, '2017-09-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Xselvox', 12, '2017-10-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Aespa', 13, '2017-11-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Bergart', 13, '2017-12-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Capa-x', 13, '2018-01-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Checho-[Rub]', 13, '2018-02-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Chikostroke', 13, '2018-03-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Dios-Zeuus', 13, '2018-04-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Docteur-Yovgn', 13, '2018-05-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Drakx-Warriorx', 13, '2018-06-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('El-Guandolo', 13, '2018-07-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Fhanel', 13, '2018-08-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Huerfanita', 13, '2018-09-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Hydra-Ra', 13, '2018-10-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Igne-Yp', 13, '2018-11-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Ishield', 13, '2018-12-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Jauzika', 13, '2019-01-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Kayzardirex', 13, '2019-02-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Kurali', 13, '2019-03-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Laryxa', 13, '2019-04-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Murra', 13, '2019-05-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Nocryball', 13, '2019-06-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Notoriouz-Big', 13, '2019-07-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Noxemo', 13, '2019-08-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Pan-tufia', 13, '2019-09-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Pink-Poison', 13, '2019-10-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Pogle', 13, '2019-11-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Pogokiu', 13, '2019-12-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Scintillating-blow', 13, '2020-01-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Sharyne', 13, '2020-02-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Shingekii', 13, '2020-03-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Sombratrop', 13, '2020-04-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('The-Football-Coach', 13, '2020-05-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Theturkey', 13, '2020-06-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Wolfcor', 13, '2020-07-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Xphantomg', 13, '2020-08-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Young-guns-il', 13, '2020-09-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Zetas-Zora', 13, '2020-10-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Arkhel', 15, '2020-11-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Buh-Aam', 15, '2020-12-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Quilowat', 16, '2021-01-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Ahuramazda', 17, '2021-02-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Blondiechan', 17, '2021-03-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Chary-Cur', 17, '2021-04-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Chary-Escudos', 17, '2021-05-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Docteur-Doflamingo', 17, '2021-06-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Estebo-J', 17, '2021-07-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Eve-Arc', 17, '2021-08-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Fra-Enitx', 17, '2021-09-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Fushoulu', 17, '2021-10-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Hankya', 17, '2021-11-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Hecaxt', 17, '2021-12-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Il-Sejmet-II', 17, '2022-01-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Kiizah', 17, '2022-02-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('King-telord', 17, '2022-03-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Kirito-Clown', 17, '2022-04-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Madam-Summoner', 17, '2022-05-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Mariaa-P', 17, '2022-06-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Maryrunas', 17, '2022-07-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Maykol-blue', 17, '2022-08-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Metrodora', 17, '2022-09-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Miocrita', 17, '2022-10-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Nightlax', 17, '2022-11-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Perrazho', 17, '2022-12-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Rayleigh-H', 17, '2023-01-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Seelfmadee', 17, '2023-02-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Tenjumer', 17, '2023-03-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Yallo', 17, '2023-04-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Zaha-hadid', 17, '2023-05-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Zvita', 17, '2023-06-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Arribamasiahc', 18, '2023-07-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Awoh', 18, '2023-08-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Bri-tt', 18, '2023-09-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Feel-The-Darkness', 18, '2023-10-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Rulof-Enu', 18, '2023-11-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Shizakura', 18, '2023-12-23');
INSERT INTO integrantes (name, rango_id, datecreate) VALUES ('Zetha', 18, '2024-01-23');