INSERT INTO rangos (nombre, control, descripcion) VALUES ('General de alianza', 1, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('General', 2, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Teniente', 3, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Coronel', 4, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Suboficial', 5, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Mayor', 6, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Capitán', 7, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Alférez', 8, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Sargento', 9, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Cabo', 10, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Diplomatico', 11, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Soldado', 12, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Milicia', 13, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Civil', 14, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Insubordinado', 15, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Ausente', 16, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Secundario', 17, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Aspirante', 18, 'Rango de alianza');

INSERT INTO eventos (nombre, puntos, descripcion) VALUES ('defprismaganada', 6, 'Defensa de prisma ganada');
INSERT INTO eventos (nombre, puntos, descripcion) VALUES ('avaconpelea', 5, 'AvA con pelea');
INSERT INTO eventos (nombre, puntos, descripcion) VALUES ('avasinpelea', 3, 'AvA sin pelea');
INSERT INTO eventos (nombre, puntos, descripcion) VALUES ('defensapercoganada', 3, 'Defensa de recaudador ganada');
INSERT INTO eventos (nombre, puntos, descripcion) VALUES ('defprismaperdida', 2, 'Defensa de prisma perdida');
INSERT INTO eventos (nombre, puntos, descripcion) VALUES ('ataqueprisma', 2, 'Ataque a prisma ganado');
INSERT INTO eventos (nombre, puntos, descripcion) VALUES ('ataqueperco', 1, 'Ataque a recaudador ganado');
INSERT INTO eventos (nombre, puntos, descripcion) VALUES ('prismaviable', 1, 'Encontrar prisma viable');
INSERT INTO eventos (nombre, puntos, descripcion) VALUES ('reciclado', 1, 'Reciclado');

INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Avalonicus', 1, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Ammy', 2, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Vulnerant', 2, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Eira-vp', 3, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Kirito-klein', 3, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Mauruz', 3, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Adhemetra', 5, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Elvulne', 5, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Lewans', 5, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Tank-Mauruz', 5, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('The-Mauruz', 5, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Vickypi', 5, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Vulnerant-lil', 5, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Cronology', 6, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Estevi', 6, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Frashirama', 6, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Stiv-xx', 7, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Xvita', 7, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Eucaristia', 8, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Moneda-xdd', 8, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Omegasxx', 8, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Chimuelooh', 9, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Koolhaas', 9, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Nowiie', 9, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Sramar', 9, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Atabex', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Chaapaa', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Chary', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Dark-pizarro', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Drajomut', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Kugh', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Mifequita', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Mr-Tymo', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Nyitiac', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Skurah', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('The-Flynn', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Ukami', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Yatanokagami', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Assesain', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Eve-Ani', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Ffelipe', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Frodobolson', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Gabilinda', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Hare-jp', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Helenthile', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Herakles-Tsuk', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Jack-frostt', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Kefi-[Rub]', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Na-bolom', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Nattew-Zoldyck', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Nightzel', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Okhoye', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Pandita-Milagrosa', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Primm-[Rub]', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Razoback', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Serindipia', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Son-Eternal', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Taisuki', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Trafalgar-A', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Verliebtheit', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Wololo-Knight', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Xselvox', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Aespa', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Bergart', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Capa-x', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Checho-[Rub]', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Chikostroke', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Dios-Zeuus', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Docteur-Yovgn', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Drakx-Warriorx', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('El-Guandolo', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Fhanel', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Huerfanita', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Hydra-Ra', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Igne-Yp', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Ishield', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Jauzika', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Kayzardirex', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Kurali', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Laryxa', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Murra', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Nocryball', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Notoriouz-Big', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Noxemo', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Pan-tufia', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Pink-Poison', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Pogle', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Pogokiu', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Scintillating-blow', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Sharyne', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Shingekii', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Sombratrop', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('The-Football-Coach', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Theturkey', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Wolfcor', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Xphantomg', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Young-guns-il', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Zetas-Zora', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Arkhel', 15, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Buh-Aam', 15, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Quilowat', 16, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Ahuramazda', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Blondiechan', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Chary-Cur', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Chary-Escudos', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Docteur-Doflamingo', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Estebo-J', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Eve-Arc', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Fra-Enitx', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Fushoulu', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Hankya', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Hecaxt', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Il-Sejmet-II', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Kiizah', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('King-telord', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Kirito-Clown', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Madam-Summoner', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Mariaa-P', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Maryrunas', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Maykol-blue', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Metrodora', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Miocrita', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Nightlax', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Perrazho', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Rayleigh-H', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Seelfmadee', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Tenjumer', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Yallo', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Zaha-hadid', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Zvita', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Arribamasiahc', 18, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Awoh', 18, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Bri-tt', 18, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Feel-The-Darkness', 18, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Rulof-Enu', 18, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Shizakura', 18, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Zetha', 18, '2024-02-20');