INSERT INTO rangos (nombre, control, descripcion) VALUES ('General de alianza', 1, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('General', 2, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Teniente', 3, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Coronel', 4, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Suboficial', 5, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Mayor', 6, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Capitán', 7, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Alférez', 8, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Sargento', 9, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Cabo', 10, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Diplomatico', 11, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Soldado', 12, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Milicia', 13, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Civil', 14, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Insubordinado', 15, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Ausente', 16, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Secundario', 17, 'Rango de alianza');
INSERT INTO rangos (nombre, control, descripcion) VALUES ('Aspirante', 18, 'Rango de alianza');

INSERT INTO eventos (nombre, puntos, descripcion) VALUES ('defprismaganada', 6, 'Defensa de prisma ganada');
INSERT INTO eventos (nombre, puntos, descripcion) VALUES ('avaconpelea', 5, 'AvA con pelea');
INSERT INTO eventos (nombre, puntos, descripcion) VALUES ('avasinpelea', 3, 'AvA sin pelea');
INSERT INTO eventos (nombre, puntos, descripcion) VALUES ('defpercoganada', 3, 'Defensa de recaudador ganada');
INSERT INTO eventos (nombre, puntos, descripcion) VALUES ('defpercoperdida', 1, 'Defensa de recaudador perdida');
INSERT INTO eventos (nombre, puntos, descripcion) VALUES ('defprismaperdida', 2, 'Defensa de prisma perdida');
INSERT INTO eventos (nombre, puntos, descripcion) VALUES ('ataqueprisma', 2, 'Ataque a prisma ganado');
INSERT INTO eventos (nombre, puntos, descripcion) VALUES ('ataqueperco', 1, 'Ataque a recaudador ganado');
INSERT INTO eventos (nombre, puntos, descripcion) VALUES ('prismaviable', 1, 'Encontrar prisma viable');
INSERT INTO eventos (nombre, puntos, descripcion) VALUES ('reciclado', 1, 'Reciclado');

INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Avalonicus', 1, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Ammy', 2, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Vulnerant', 2, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Eira-vp', 3, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Kirito-klein', 3, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Mauruz', 3, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Sramar', 4, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Cronology', 6, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Estevi', 6, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Frashirama', 6, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Stiv-xx', 7, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Xvita', 7, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Chimuelooh', 8, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Eucaristia', 8, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Moneda-xdd', 8, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Omegasxx', 8, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Koolhaas', 9, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Mr-Tymo', 9, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Nowiie', 9, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Assesain', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Atabex', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Chaapaa', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Chary', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Drajomut', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Gabilinda', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Kugh', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Mifequita', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Pogle', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Puzzi', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Skurah', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('The-Flynn', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Ukami', 10, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Balim-[Rub]', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Bergart', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Chikostroke', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Dark-pizarro', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Eve-Ani', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Ffelipe', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Frodobolson', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Hare-jp', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Helenthile', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Hydra-Ra', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Jack-frostt', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Kayzardirex', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Kefi-[Rub]', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Kuraii', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Na-bolom', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Nattew-Zoldyck', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Nightzel', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Okhoye', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Pan-tufla', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Pandita-Milagrosa', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Primm-[Rub]', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Quilowat', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Razoback', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Son-Eternal', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Taisuki', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Trafalgar-A', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Verliebtheit', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Wololo-Knight', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Xselvox', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Young-guns-ll', 12, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Aespa', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Arribamasiahc', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Capa-x', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Checho-[Rub]', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Dios-Zeuus', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Docteur-Yovgn', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('El-Guandolo', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Feel-The-Darkness', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Fhanel', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Igne-Yp', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Jauzika', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('King-telord', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Laryxa', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Murra', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Nocryball', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Notoriouz-Big', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Noxemo', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Pogokiu', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Scintillating-blow', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Sharyne', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Shingekii', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Theturkey', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Wolfcor', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Xphantomg', 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Arkhel', 15, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Buh-Aam', 15, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Herakles-Tsuk', 15, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Awoh', 18, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Kasutc', 18, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Mitenss', 18, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Psycho-Batto', 18, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Rulof-Enu', 18, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Shizakura', 18, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Zetha', 18, '2024-02-20');

INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Adhemetra', 5, 2, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Elvulne', 5, 3,'2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Esquizob', 5, 3, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Gxto', 5, 6, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Kirito-Clown', 5, 5, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Lewans', 5, 2, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Mauruz-Yt', 5, 6, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Vickypi', 5, 4, '2024-02-20');

INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Ahuramazda', 17, 59, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Blondiechan', 17, 39, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Chary-Cur', 17, 33, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Chary-Escudos', 17, 33, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Docteur-Doflamingo', 17, 68, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Estebo-J', 17, 9, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Eve-Arc', 17, 37, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Freya-Lodbrok', 17, 7, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Fushoulu', 17, 41, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Hankya', 17, 31, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('il-Sejmet-il', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Kayzarcra', 17, 44,'2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Kiizah', 17, 30, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Kugh-curas', 17, 36, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Latalibana', 17, 20, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Mariaa-P', 17, 80, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Maryrunas', 17, 42, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Master-nemexis', 17, 13, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Miocrita', 17, 27, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Nightlax', 17, 49, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Rayleigh-H', 17, 58, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Tenjumer', 17, 28, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Yallo', 17, 22, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Zaha-hadid', 17, 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, fechacreacion) VALUES ('Zei-Ocrix', 17, '2024-02-20');
INSERT INTO integrantes (nombre, rango_id, principal_id, fechacreacion) VALUES ('Zvita', 17, 12, '2024-02-20');